name: Release

on:
  release:
    types:
      - created

jobs:
  dist_linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: crystallang/crystal:latest-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: crystal build --release hexdumb.cr && strip hexdumb
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./hexdumb
        asset_name: hexdumb-${{ github.event.release.tag_name }}-linux-x86_64
        asset_content_type: binary/octet-stream
